"""changing

Revision ID: 5404bd4bcab9
Revises:
Create Date: 2026-06-01 21:50:04.499326

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5404bd4bcab9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("checkpoint_blobs_thread_id_idx"), table_name="checkpoint_blobs")
    op.drop_table("checkpoint_blobs")
    op.drop_index(op.f("checkpoints_thread_id_idx"), table_name="checkpoints")
    op.drop_table("checkpoints")
    op.drop_table("checkpoint_migrations")
    op.drop_index(
        op.f("checkpoint_writes_thread_id_idx"), table_name="checkpoint_writes"
    )
    op.drop_table("checkpoint_writes")
    op.drop_constraint(op.f("api_keys_user_id_fkey"), "api_keys", type_="foreignkey")
    op.create_foreign_key(
        None, "api_keys", "users", ["user_id"], ["userid"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("config_user_id_fkey"), "config", type_="foreignkey")
    op.create_foreign_key(
        None, "config", "users", ["user_id"], ["userid"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("knowledge_bases_user_id_fkey"), "knowledge_bases", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "knowledge_bases", "users", ["user_id"], ["userid"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("mcp_config_user_id_fkey"), "mcp_config", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "mcp_config", "users", ["user_id"], ["userid"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("messages_session_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(
        None, "messages", "sessions", ["session_id"], ["session_id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("sessions_kb_id_fkey"), "sessions", type_="foreignkey")
    op.drop_constraint(op.f("sessions_user_id_fkey"), "sessions", type_="foreignkey")
    op.create_foreign_key(
        None, "sessions", "users", ["user_id"], ["userid"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "sessions", "knowledge_bases", ["kb_id"], ["kb_id"], ondelete="SET NULL"
    )
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("sessions_user_id_fkey"), "sessions", "users", ["user_id"], ["userid"]
    )
    op.create_foreign_key(
        op.f("sessions_kb_id_fkey"), "sessions", "knowledge_bases", ["kb_id"], ["kb_id"]
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_session_id_fkey"),
        "messages",
        "sessions",
        ["session_id"],
        ["session_id"],
    )
    op.drop_constraint(None, "mcp_config", type_="foreignkey")
    op.create_foreign_key(
        op.f("mcp_config_user_id_fkey"), "mcp_config", "users", ["user_id"], ["userid"]
    )
    op.drop_constraint(None, "knowledge_bases", type_="foreignkey")
    op.create_foreign_key(
        op.f("knowledge_bases_user_id_fkey"),
        "knowledge_bases",
        "users",
        ["user_id"],
        ["userid"],
    )
    op.drop_constraint(None, "config", type_="foreignkey")
    op.create_foreign_key(
        op.f("config_user_id_fkey"), "config", "users", ["user_id"], ["userid"]
    )
    op.drop_constraint(None, "api_keys", type_="foreignkey")
    op.create_foreign_key(
        op.f("api_keys_user_id_fkey"), "api_keys", "users", ["user_id"], ["userid"]
    )
    op.create_table(
        "checkpoint_writes",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("idx", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column(
            "task_path",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "checkpoint_id",
            "task_id",
            "idx",
            name=op.f("checkpoint_writes_pkey"),
        ),
    )
    op.create_index(
        op.f("checkpoint_writes_thread_id_idx"),
        "checkpoint_writes",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "checkpoint_migrations",
        sa.Column("v", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("v", name=op.f("checkpoint_migrations_pkey")),
    )
    op.create_table(
        "checkpoints",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "parent_checkpoint_id", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "checkpoint",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id", "checkpoint_ns", "checkpoint_id", name=op.f("checkpoints_pkey")
        ),
    )
    op.create_index(
        op.f("checkpoints_thread_id_idx"), "checkpoints", ["thread_id"], unique=False
    )
    op.create_table(
        "checkpoint_blobs",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("version", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "channel",
            "version",
            name=op.f("checkpoint_blobs_pkey"),
        ),
    )
    op.create_index(
        op.f("checkpoint_blobs_thread_id_idx"),
        "checkpoint_blobs",
        ["thread_id"],
        unique=False,
    )
    # ### end Alembic commands ###
